fs:
  image: tianon/true
  volumes:
    - ./mysql-datadir:/var/lib/mysql
    - ./mysql-shr:/shr
    - ./mysql-autoload:/docker-entrypoint-initdb.d:ro

db:
  image: mysql
  environment:
    - TZ=Europe/Stockholm
    - MYSQL_ROOT_PASSWORD=password12
    - MYSQL_DATABASE=keycloak
    - MYSQL_USER=keycloak
    - MYSQL_PASSWORD=keycloak 
  volumes_from:
    - fs
 
sso:
  build: sso
  environment:
    - TZ=Europe/Stockholm
    - MYSQL_DATABASE=keycloak
    - MYSQL_USERNAME=keycloak
    - MYSQL_PASSWORD=keycloak 
  ports:
    - "8080:8080"
  links:
    - db:mysql  
  volumes_from:
    - fs
 

 
